### ISSUE TITLE
Améliorer la vocalisation de la saisie des types de ressources

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#300]
- [x] Vocalisation de l'accordéon comme un jeu d'onglets : #329.
- [x] Vocalisation des titres de l'accordéon en doublon : nécessite un test sur NVDA : #350 a priori.
- [x] Vocalisation des types de ressources comme des cases à cocher : #350.
- [x] ~~Renommer le bouton « Valider » ?~~ → Compliqué, car « Déclarer les montants » ne fonctionne pas si aucune ressource n'est sélectionnée, par exemple. Changer le nom du bouton de validation en cours d'interaction semble une mauvaise pratique.

**Comment by fpagnoux** [comment]
Cases à cocher

**Comment by fpagnoux** [comment]
Pas de  vocalisation en doublon  avec voiceover.
Les titres contiennent un lien composé d' un `<span>` (le texte) et d'un `<i>` ( l'icône). Je ne vois rien d'évident à améliorer. 
Le dédoublement apparaît comme un comportement erroné de NVDA.

D'après mes souvenirs, le plus perturbant était que lorsque l'utilisateur mettait le focus sur le chevron, il n'avait aucune information audio explicite. Si on ne peut pas empêcher le dédoublement, il faudrait au moins que la vocalisation soit plus explicite sur le chevron.

Par ailleurs, on peut améliorer l'accessibilité de l'accordéon avec de l'[ARIA](https://www.w3.org/TR/wai-aria-practices/#accordion) ou en regardant  du côté du [plugin accessibilité bootstrap](https://github.com/paypal/bootstrap-accessibility-plugin).

**Comment by fpagnoux** [comment]
Un `aria-hidden` pourrait permettre de cacher le chevron.

**Comment by fpagnoux** [comment]
Difficile d'ajouter les tags aria alors qu'angular-bootstrap compile les `<accordion>` en d'autres tags.

**Comment by fpagnoux** [comment]
Updating `angular-bootstrap` could solve a lot of accessibility issues, but doing so without updating angular can be complicated.
